#stage
version: "3.9"

services:
  frontend-part:
    image: alonimacaroni/vote-frontend:stage
    build:
      context: ./frontend-ui/
      target: prod-stage
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-part.entrypoints=websecure"
      - "traefik.http.routers.frontend-part.rule=Host(`${DOMAIN_URL}`, `www.${DOMAIN_URL}`)"
      - "traefik.http.routers.frontend-part.tls.certresolver=myresolver"
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./frontend-ui:/app
    security_opt:
      - no-new-privileges:true
  
  vote-app-mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
      - mysql:/var/lib/mysql:delegated
      - ./db_assets:/docker-entrypoint-initdb.d/:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    security_opt:
      - no-new-privileges:true
  
  backend-part:
    image: alonimacaroni/vote-backend:latest
    build:
      context: ./vote_app_backend/
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.backend-part.entrypoints=websecure"
      - "traefik.http.routers.backend-part.rule=Host(`${DOMAIN_URL}`, `www.${DOMAIN_URL}`) && PathPrefix(`/${URI_ENTRYP_PATH}`)"
      - "traefik.http.routers.backend-part.tls.certresolver=myresolver"
    restart: unless-stopped
    command: >
      sh -c 'gunicorn vote_app_backend.wsgi:application --workers 3 --bind :8000'
    # command: >
    #   sh -c 'gunicorn --workers 3 --bind unix:~/janina.devcon.team/janina-voting-app/vote_app_backend/vote_app_backend.sock vote_app_backend.wsgi:application'
    networks:
      - proxy
    volumes:
      - ./vote_app_backend:/code
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
      - URI_ENTRYP_PATH=${URI_ENTRYP_PATH}
      - URI_CSRF_PATH=${URI_CSRF_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
    security_opt:
      - no-new-privileges:true
    depends_on:
      - vote-app-mysql
  
  proxy-part:
    image: traefik:v2.7
    restart: unless-stopped
    #static configuration
    command: >-
      --log.level=DEBUG
      --api.dashboard=true
      --api.insecure=true
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
      --entrypoints.web.http.redirections.entrypoint.to=websecure
      --entrypoints.web.http.redirections.entrypoint.scheme=https
      --entrypoints.websecure.address=:443
      --certificatesresolvers.myresolver.acme.tlschallenge=true
      --certificatesresolvers.myresolver.acme.email=schroeder@convidera.com
      --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
#      --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory  
    ## don't do this in production:
    #  --api.dashboard=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-part.entrypoints=websecure"
      - "traefik.http.routers.proxy-part.service=api@internal"
      - "traefik.http.routers.proxy-part.rule=Host(`dash.${DOMAIN_URL}`, `www.dash.${DOMAIN_URL}`)"
      - "traefik.http.routers.proxy-part.tls.certresolver=myresolver"
#      - "traefik.http.routers.backend-part.middlewares=force-https"    
      ##  disable TLS version 1.0 and 1.1
      # - "traefik.tls.options.default.minversion=VersionTLS12"
      #configure encryption methods
      # - "traefik.http.middlewares.secureheaders.headers.browserxssfilter=true"
      # - "traefik.http.middlewares.secureheaders.headers.contenttypenosniff=true"
      # #SSL config
      # - "traefik.http.middlewares.secureheaders.headers.framedeny=true"
      # - "traefik.http.middlewares.secureheaders.headers.sslredirect=true"
      # #HSTS config
      # - "traefik.http.middlewares.secureheaders.headers.stsincludesubdomains=true"
      # - "traefik.http.middlewares.secureheaders.headers.stspreload=true"
      # - "traefik.http.middlewares.secureheaders.headers.stsseconds=31536000"
      #- "traefik.http.middlewares.secureheaders.headers.customframeoptionsvalue=SAMEORIGIN"
      # #CORS config
    #   - "traefik.http.middlewares.secureheaders.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
    #   - "traefik.http.middlewares.secureheaders.headers.accesscontrolalloworigin=origin-list-or-null"
    #   - "traefik.http.middlewares.secureheaders.headers.accesscontrolmaxage=100"
    #   - "traefik.http.middlewares.secureheaders.headers.addvaryheader=true"
    # security_opt:
      - no-new-privileges:true
    #settings for mkcert, self-signed certs should be used locally (not letsencrypt)
    #letsencrypt needs to establish a connection via the http challenge
    #mkcert creates a cert and installs a CA locally
    #certificateresolver is only needed with letsencrypt
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    #dynamic configuration
    networks:
      - proxy
    volumes: 
      - ./.deploy/stage/letsencrypt:/letsencrypt
      #if you are using Docker as your provider
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    driver: bridge
  # proxy:
  #   external: true

volumes:
  mysql:
    driver: local